### ISSUE TITLE
Provide a way to enable or disable logging

### ISSUE THREAD

**Issue by josuebrunel** [josuebrunel/yahoo-oauth#33]

**Comment by LeMeteore** [comment]
> (unless the propagate flag for a logger is set to a false value, at which point the passing to ancestor handlers stops).

I think you should look at the logger's [propagate](https://docs.python.org/2/howto/logging.html) flag.

**Comment by josuebrunel** [comment]
Thanks @LeMeteore , i will try this out and keep you posted :wink:

**Comment by underdpt** [comment]
I think this isn't fully resolved. After a lot of testing, this is the only way I could disable yahoo-oauth messing with my own logger:

```python
import logging
logger = logging.getLogger('my-own-logger')
logger.propagate = False

# Disable yahoo-oauth formatter and logger
logging.setLoggerClass(logging.Logger)
```

I think yahoo-oauth should't set its own logger class unless specified (maybe some option before importing?)

**Comment by josuebrunel** [comment]
@underdpt hello. I will dig into that this weekend. Don't hesitate to propose a patch by the way.

**Comment by DMcP89** [comment]
@josuebrunel I've opened #61  to address this
