### ISSUE TITLE
Cannot access private data

### ISSUE THREAD

**Issue by ma-schmidt** [josuebrunel/yahoo-oauth#42]
Thanks for the package. I am trying to get fantasy sport data from Yahoo's API. When I try a public request (like getting the player ranking), it works and I seem to be authentified. When I try running a private request (requires https, like getting the transactions of a particular league) it fails and returns an xml response which includes (I use `oauth.session.get()`):

> Authentication Error.  The table fantasysports.leagues.transactions requires
> a higher security level than is provided, you provided ANY but at least USER is expected

Even though the message is very straghtforward, I cannot figure out what I am missing. Either I don't know how to use the package, or there is a connection problem somewhere. I go through the whole authentication process smoothly (consumer key, consumer secret, getting the PIN) and my access_token is considered valid when calling `token_is_valid()`. Is the package only good for public requests over http? I don't know what I am missing.

I have tried:
- python 2 and 3
- `OAuth1` and `OAuth2`

Thanks

**Comment by josuebrunel** [comment]
Hello @ma-schmidt can i have a code snippet please and a traceback ? Thanks

**Comment by josuebrunel** [comment]
Hello @ma-schmidt , did you fix your issue ?

**Comment by ma-schmidt** [comment]
Sorry, Yes I sort of fixed it. I was using the yql API (with the url https://query.yahooapis.com/v1/public/yql). That never worked as I explained above. When I switched to the non-yql API (with the url: https://fantasysports.yahooapis.com/fantasy/v2) everything worked.

I assumed that the problem came from my misunderstanding of the Yahoo API (I still don't understand why the first one does not work) more than your module.

Thanks!

**Comment by josuebrunel** [comment]
@ma-schmidt ok great then. Don't hesitate if you any trouble. By the way, if you're working any ***Fantasy stuff*** you can check [this](https://github.com/josuebrunel/yahoo-fantasy-sport) out. We've stopped the dev of the library, but you may be the guy to bring it back up. As soon as i have a lil spare time, i will do my best to finish it

**Comment by RichieRunner** [comment]
@ma-schmidt So how would we request data with higher required security using the yqlAPI? I have an OAuth token but can't seem to get it to work along with the yql query string.

**Comment by ma-schmidt** [comment]
@RichieRunner I have no idea. I ended up not using the YQL api and used their REST api directly from URL requests.
