### ISSUE TITLE
Gemini reports examples

### ISSUE THREAD

**Issue by kubber** [josuebrunel/yahoo-oauth#48]
Hey Josue thanks for this lib, saved me some time !

Maybe somebody's going to need some examples how to get yahoo gemini reports 
Here's what worked for me 

``` python
import urllib
import json

import time
from yahoo_oauth import OAuth2
oauth = OAuth2(None, None, from_file='credentials.json')

if not oauth.token_is_valid():
    oauth.refresh_access_token()

# get all accounts
response = oauth.session.get("https://api.admanager.yahoo.com/v1/rest/advertiser/")
data = response.content
print data
jdata = json.loads(data)
for j in jdata['response']:
    print "{} {}".format(j['id'], j['advertiserName'])


# get advertiser data
advertiser_id = 12345678
report_date_from = "2016-08-28"
report_date_to = "2016-08-28"
payload = {"cube": "performance_stats",
           "fields": [
               {"field": "Day"},
               {"field": "Impressions"},
               {"field": "Conversions"},
               {"field": "Spend"},
               {"field": "Campaign ID"}
           ],
           "filters": [
               {"field": "Advertiser ID", "operator": "=", "value": advertiser_id},
               {"field": "Day", "operator": "between", "from": report_date_from, "to": report_date_to}
           ]}

response = oauth.session.post("https://api.admanager.yahoo.com/v1/rest/reports/custom?reportFormat=json", json=payload)
print response.content

jdata = json.loads(response.content)
job_id = jdata['response']['jobId']

# you will need to add some loop and waits before the report is ready
time.sleep(60)

url = "https://api.admanager.yahoo.com/v1/rest/reports/custom/{}?advertiserId={}".format(job_id, advertiser_id)
response = oauth.session.get(url)
print response.content

# report will be returned as url
rdata = json.loads(response.content)
if 'status' in rdata['response'] and rdata['response']['status'] == 'completed':
    report = urllib.urlopen(rdata['response']['jobResponse']).read()
    print report
```

**Comment by josuebrunel** [comment]
Hi @kubber . That's great ! Thank you very much. It will definitely be helpful, since a lot are struggling with Yahoo! Gemini when using the lib. 
There's a discussion about that on #43 
Thanks again for your contribution, and have a good one. Don't hesitate to update the documentation with that exemple and submit a pull request, it will be very appreciated
Have a good one

**Comment by gigigarate** [comment]
I used your code and was able to retrieve the report but my report contains 0 rows. This is the report I get. Any help or insight on why i'm not getting any rows returned would be super helpful. Thanks

{'header': 
{'cube': 'keyword_stats', 
'fields': [
{'fieldName': 'Advertiser ID', 'fieldType': 'DIM'},
{'fieldName': 'Day', 'fieldType': 'DIM'}, 
{'fieldName': 'Clicks', 'fieldType': 'FACT'}, 
{'fieldName': 'Device Type', 'fieldType': 'FACT'},
{'fieldName': 'Conversions', 'fieldType': 'FACT'}
]
'rows': [], 
'rowCount': 0
}

**Comment by DMcP89** [comment]
Closing this issue as Yahoo has removed the Gemini API
