### ISSUE TITLE
yahoo refresh token problem

### ISSUE THREAD

**Issue by joalmjoalm** [josuebrunel/yahoo-oauth#49]
I try to run it on Ubuntu1604 towards Yahoo developer api, .https://developer.yahoo.com/oauth/guide/oauth-refreshaccesstoken.html

Everything works fine until it should refresh accesstoken when I get the error below.

I have tested to manually refresh with the help of Postman client and that works fine testing with the same credientals.

Any idea of what I can do to get it working ?

Below I test in Ubuntu from python terminal.

``` python
>>> oauth.refresh_access_token()
[2016-08-30 21:48:01,388 DEBUG] [yahoo_oauth.yahoo_oauth.refresh_access_token] REFRESHING TOKEN
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xx/.local/lib/python2.7/site-packages/yahoo_oauth/yahoo_oauth.py", line 186, in refresh_access_token
    self.access_token, self.access_token_secret = self.oauth.get_access_token(self.access_token, self.access_token_secret, params={"oauth_session_handle": self.session_handle})
  File "/home/xx/.local/lib/python2.7/site-packages/rauth/service.py", line 332, in get_access_token
    process_token_request(r, decoder, key_token, key_token_secret)
  File "/home/xx/.local/lib/python2.7/site-packages/rauth/service.py", line 24, in process_token_request
    raise KeyError(PROCESS_TOKEN_ERROR.format(key=bad_key, raw=r.content))
KeyError: 'Decoder failed to handle oauth_token with data as returned by provider. A different decoder may be needed. Provider returned: oauth_problem=signature_invalid'
>>>
```

**Comment by josuebrunel** [comment]
Hi @joalmjoalm, 
I haven't been able to reproduce the bug. I might need more than this trace. thanks

**Comment by josuebrunel** [comment]
@joalmjoalm 
My bad, i have been able to reproduce the error while using python3. I'm gonna dig into that. Thanks for the report mate

**Comment by josuebrunel** [comment]
It's weird i haven't changed a thing in the code. As a workaround, what you can do, is to reset your credentials by removing *access_token* and *access_token_secret* in your file. Mine were more than a year old and it didn't work either. I reset my credentials and everything seems to be fine. 
Keep me posted
