### ISSUE TITLE
KeyError: 'xoauth_yahoo_guid'

### ISSUE THREAD

**Issue by JeMorriso** [josuebrunel/yahoo-oauth#54]
Hi, thanks for your work on this project. 

I'm having an issue with authorisation of my yahoo app. Specifically, I am given the authorisation url, and I enter the code to connect and I am getting the following traceback: 

```python
  File "/home/jerry/.local/share/virtualenvs/In-it-to-Winnik-V2oo3_u6/lib/python3.8/site-packages/yahoo_oauth/yahoo_oauth.py", line 229, in __init__
    super(OAuth2, self).__init__('oauth2', consumer_key, consumer_secret, **kwargs)
  File "/home/jerry/.local/share/virtualenvs/In-it-to-Winnik-V2oo3_u6/lib/python3.8/site-packages/yahoo_oauth/yahoo_oauth.py", line 89, in __init__
    data.update(self.handler()) 
  File "/home/jerry/.local/share/virtualenvs/In-it-to-Winnik-V2oo3_u6/lib/python3.8/site-packages/yahoo_oauth/yahoo_oauth.py", line 143, in handler
    credentials.update(self.oauth2_access_parser(raw_access))
  File "/home/jerry/.local/share/virtualenvs/In-it-to-Winnik-V2oo3_u6/lib/python3.8/site-packages/yahoo_oauth/yahoo_oauth.py", line 165, in oauth2_access_parser
    self.guid = parsed_access['xoauth_yahoo_guid']
KeyError: 'xoauth_yahoo_guid'
```
The weird thing is that authorizing works perfectly fine with a yahoo app that I set up 2 months ago, but it refuses to work with any new apps that I have created today. Thanks again for your help.

**Comment by JeMorriso** [comment]
I just realized I'm using the version on pypi which was released in 2015 so I will have to try cloning this repo.

**Comment by josuebrunel** [comment]
Hi. I'll look into that. I don't think the latest commits will change anything. 
Hopefully I will figure it out and upload the library today.

**Comment by JeMorriso** [comment]
Thanks Josue!

**Comment by craigham** [comment]
I was getting this error as well last week.  I think I saw it when I tried to create a new yahoo app and use it.  Best I could figure out is Yahoo changed the requirements around specifying the redirect url.  Bottom line I couldn't get a json file with the access token and other items with a new app, but could with an app I had created 2 years ago.

**Comment by Imoustak** [comment]
Hey, I am experiencing exactly the same issue trying to authenticate with yahoo. I tried both with an old app that I had and a newly created one. Did you guys managed to solve this somehow? 
Any input would be welcome. Thanks!

**Comment by mrollo** [comment]
I'm getting the same error. I don't have an old app to try with, but I've created a few new apps, tried configuring the app to have varying levels of access to different things in the user's profile, but the xoauth_yahoo_guid is never returned in the response from /get_token.

**Comment by josuebrunel** [comment]
Hello, sorry for the delay. I needed to take a break. I'll look into that as soo as possibel

**Comment by mrollo** [comment]
[Yahoo's documentation](https://developer.yahoo.com/oauth2/guide/openid_connect/getting_started.html) doesn't say anything about the xoauth_yahoo_guid being optional in the response, so this is really on Yahoo. But perhaps this library can treat the response param as optional not not fail if it's not included in the response.

**Comment by gerinski** [comment]
Hey guys, I'm also facing exacly the same issue on my side. Are there any updates?

**Comment by josuebrunel** [comment]
Hello. A lot of stuff at work lately. I promise to take a look at it this weekend

**Comment by JunOgawa** [comment]
Hi,
I'm getting the this error on my new app. Does someone solve this problem?

**Comment by sarys19** [comment]
Hey guys, any update?

**Comment by JunOgawa** [comment]
As a temporal solution, try to comment out the followings in yahoo_oauth.py:
L165    self.guid = parsed_access['xoauth_yahoo_guid']
L171    'guid': self.guid
In my case, this works.

**Comment by josuebrunel** [comment]
Hi, really sorry for the delay. I just applied a patch and will release a new version in a moment. 
I'm working on a new and more convenient version of the lib and I hope it will be done very soon

**Comment by josuebrunel** [comment]
the *1.0* version is published

**Comment by mrollo** [comment]
No need to apologize @josuebrunel - you're the one doing the work! Thank you!

**Comment by sarys19** [comment]
We appreciate it Josue!  I'm still getting the error, however

**Comment by sarys19** [comment]
This may be related to the redirect URL in app registration.  What address should I use for local?  is http accepted?  Or only https

**Comment by josuebrunel** [comment]
@sarys19 is the error still related to the key ?
For local you can use `callback_uri='oob'`as described [here](https://developer.yahoo.com/oauth2/guide/flows_authcode/).

By the way, you guys should check [this](https://developer.yahoo.com/oauth2/guide/flows_authcode/)

**Comment by JunOgawa** [comment]
Thank you, @josuebrunel
It works perfectly.
