### ISSUE TITLE
Using this library with access_token and refresh_token

### ISSUE THREAD

**Issue by jakubigla** [josuebrunel/yahoo-oauth#60]
How to use this library (non interactively)when having `access_token` and `refresh_token`?
I obtained these using this flow: https://developer.yahoo.com/oauth2/guide/flows_authcode/

I need this to use this library: https://github.com/spilchen/yahoo_fantasy_api/

**Comment by josuebrunel** [comment]
Hello @jakubigla ,
I think you can pass a `from_file` param just like [here](https://github.com/josuebrunel/yahoo-oauth/blob/master/tests.py#L36)
You might need to have file which looks like this 

```json
{
   "access_token": "xxxxx",
   "client_id": "xxxx",
   "client_secret": "xxxxx",
   "refresh_token": "xxxx" 
}
```
When using, the lib can add other fields to this file.

**Comment by jakubigla** [comment]
Hi @josuebrunel thanks for responding so quickly.
I'm aware of this `from_file` parameter, but I keep all my credentials in the database. Does it mean I need to create a physical file in order to use it non-interactively? Not a Python expert but maybe there's some in-memory option type of the file I an pass to the `from_file` parameter?

**Comment by josuebrunel** [comment]
Ok, I see. Hum, I think you can try passing them as `args` while instantiating your service

```python
s = OAuth2(client_id, client_secret, access_token, ...)
```

Sorry can't test because I lost my credentials. 
By the way, I don't maintain it anymore, but I'll take a better look if I can this weekend

**Comment by jakubigla** [comment]
yea, I tried this:
```
oauth = OAuth2(
  consumer_key=YAHOO_CLIENT_ID, 
  consumer_secret=YAHOO_CLIENT_SECRET, 
  access_token = auth_data["access_token"], 
  refresh_token = auth_data["refresh_token"]
)
```
but it keeps open the browser and expects the code

**Comment by josuebrunel** [comment]
Ok, I think you'll need to create a `wrapper` class that inherit from `BaseOAuth`



```python
from yahoo_oauth.oauth import BaseOAuth

class Wrapper(BaseOAuth):
       def __init__(self, consumer_key, consumer_secret, access_token, refresh_token, ..):
             self.consumer_key = consumer_key
             self.consumer_secret = consumer_secret
             # do the same for the rest of the attributes 
```

You just have to make sure that your `wrapper` statisfies https://github.com/josuebrunel/yahoo-oauth/blob/master/yahoo_oauth/oauth.py#L183

Once it does, you can do things like 

```python
w = Wrapper(....)
w.refresh_token()
```

Good luck

**Comment by DMcP89** [comment]
@jakubigla I've implemented using a db to store OAuth Credentials in my [harambot project](https://github.com/DMcP89/harambot).

I have a util function that handles retrieving the OAuth tokens:
```
def yahoo_auth(code):
    encoded_creds = base64.b64encode(
        ("{0}:{1}".format(settings.yahoo_key, settings.yahoo_secret)).encode(
            "utf-8"
        )
    )
    details = requests.post(
        url="{}get_token".format(YAHOO_API_URL),
        data={
            "code": code,
            "redirect_uri": "oob",
            "grant_type": "authorization_code",
        },
        headers={
            "Authorization": "Basic {0}".format(encoded_creds.decode("utf-8")),
            "Content-Type": "application/x-www-form-urlencoded",
        },
    ).json()

    details["token_time"] = time.time()
    return details
```
https://github.com/DMcP89/harambot/blob/main/harambot/utils.py

and I'm using peewee as an ORM and I store everything I get back from the initial OAuth request:
```
class Guild(BaseModel):
    guild_id = TextField(unique=True)
    access_token = TextField()
    refresh_token = TextField()
    expires_in = IntegerField()
    token_type = TextField()
    xoauth_yahoo_guid = TextField(null=True)
    token_time = BigIntegerField()
    league_id = TextField()
    league_type = TextField()
    RIP_text = TextField()
    RIP_image_url = TextField()
    last_transaction_check = TimestampField()
```
https://github.com/DMcP89/harambot/blob/main/harambot/database/models.py

When I need to create an OAuth object I pass it the entire guild object and convert it to a dict:
```
    async def set_yahoo_from_interaction(
        self, interaction: discord.Interaction
    ):
        guild = Guild.get(Guild.guild_id == str(interaction.guild_id))
        self.yahoo_api = Yahoo(
            OAuth2(
                self.KEY, self.SECRET, store_file=False, **model_to_dict(guild)
            ),
            guild.league_id,
            guild.league_type,
        )
        return
```
https://github.com/DMcP89/harambot/blob/main/harambot/cogs/yahoo.py

Hope this helps.
