### ISSUE TITLE
Not compatible with AWS lambda

### ISSUE THREAD

**Issue by zevpermack** [josuebrunel/yahoo-oauth#66]
I am using this library and uploading my lambda as a docker image on ECR and the load that image on lambda. 
I want this function to run once a day but I am getting an error where the library seems to want to write to a root directory to `secrets.json` in the lambda environment. 
In a lambda environment you can only write to tmp files in temp folder but yahoo-oauth is trying to write to `secrets.json` in the root directory. Any thoughts on how the library could accommodate this?

**Comment by DMcP89** [comment]
Hi @zevpermack 

This file is created by default to store the OAuth session data. You can use the store_file option to avoid having secrets.json created:
```
 OAuth2( KEY, self.SECRET, store_file=False )
```
