### ISSUE TITLE
Unable to get GUID

### ISSUE THREAD

**Issue by chuanyao17** [josuebrunel/yahoo-oauth#69]
```
from yahoo_oauth import OAuth2
import yahoo_fantasy_api as yfa

#connect to yahoo api
oauth = OAuth2('consumer_key', 'consumer_secret')
guid = oauth.guid
print(guid)
#get game object
gm = yfa.Game(oauth, 'nba')
leagues = gm.league_ids()
print(leagues)
```
After I executed the above code using my consumer_key' and 'consumer_secret, I was able to print the league ID, but the result of guid is null. 
How can I get the guid?
Thanks

**Comment by DMcP89** [comment]
The Yahoo OAuth API no longer returns a xoauth_yahoo_guid when authenticating which is what normally populates the guid field.  The only fields returned now are access_token, refresh_token, expiers_in, and token_type:
```
{
	"access_token": "*********************************************************************************",
	"refresh_token": "*********************************************************************************",
	"expires_in": 3600,
	"token_type": "bearer"
}
```
Will open a ticket to have the guid handling removed.
